version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:12.16.2
    working_directory: ~/repo

jobs:
  danger:
    executor: default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "1c:73:2b:df:00:39:30:ba:11:80:62:e9:a8:79:64:1a"
      - run:
          name: Danger
          command: yarn danger ci

workflows:
  welcome:
    jobs:
      - danger
