version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:12.16.2

jobs:
  danger:
    executor: default
    steps:
      - run:
          name: Danger
          command: yarn danger ci

workflows:
  welcome:
    jobs:
      - danger
